### ISSUE TITLE
Mod Rewrite Middleware Checklist

### ISSUE THREAD

**Issue by ZestyBread** [aspnet/BasicMiddleware#66]
Features implemented in mod_rewrite:

- [ ] RewriteBase
- [ ] RewriteCond
- [ ] RewriteRule
- [ ] RewriteMap
- [ ] RewriteEngine
- [ ] RewriteOptions
Flags
- [ ] Escape Back References
- [ ] Chain
- [ ] Cookie
- [ ] Discard Path
- [ ] Env
- [ ] End
- [ ] Forbidden
- [ ] Gone
- [ ] Handler
- [ ] Last
- [ ] Next
- [ ] No Case
- [ ] No Escape
- [ ] No Subrequest
- [ ] Proxy
- [ ] Pass Through
- [ ] Query String Append
- [ ] Query String Delete
- [ ] Query String Last
- [ ] Redirect
- [ ] Skip
- [ ] Type

Server Variables

- [ ] HTTP_ACCEPT
- [ ] HTTP_COOKIE
- [ ] HTTP_FORWARDED
- [ ] HTTP_HOST
- [ ] HTTP_PROXY_CONNECTION
- [ ] HTTP_REFERER
- [ ] HTTP_USER_AGENT
- [ ] AUTH_TYPE
- [ ] CONN_REMOTE_ADDR
- [ ] CONTEXT_PREFIX
- [ ] CONTEXT_DOCUMENT_ROOT
- [ ] IPV6
- [ ] PATH_INFO
- [ ] QUERY_STRING
- [ ] REMOTE_ADDR
- [ ] REMOTE_HOST
- [ ] REMOTE_IDENT
- [ ] REMOTE_PORT
- [ ] REMOTE_USER
- [ ] REQUEST_METHOD
- [ ] SCRIPT_FILENAME
- [ ] DOCUMENT_ROOT
- [ ] SCRIPT_GROUP
- [ ] SCRIPT_USER
- [ ] SERVER_ADDR
- [ ] SERVER_ADMIN
- [ ] SERVER_NAME
- [ ] SERVER_PORT
- [ ] SERVER_PROTOCOL
- [ ] SERVER_SOFTWARE
- [ ] TIME_YEAR
- [ ] TIME_MON
- [ ] TIME_DAY
- [ ] TIME_HOUR
- [ ] TIME_MIN
- [ ] TIME_SEC
- [ ] TIME_WDAY
- [ ] TIME
- [ ] API_VERSION
- [ ] CONN_REMOTE_ADDR
- [ ] HTTPS
- [ ] IS_SUBREQ
- [ ] REMOTE_ADDR
- [ ] REQUEST_FILENAME
- [ ] REQUEST_SCHEME
- [ ] REQUEST_URI
- [ ] THE_REQUEST
- [ ] Segmented Lookups (Ex HTTP:header) 

CondPattern
- [ ] Integer Comparison
- [ ] String Comparison
- [ ] Is File
- [ ] Is Directory
- [ ] Size
- [ ] Existing Url via subrequest
- [ ] Executable
- [ ] Symbolic Link

**Comment by ZestyBread** [comment]
This will be updated on completion of more features/ deciding if features will not be supported.

**Comment by ZestyBread** [comment]
:up: :date: to this list.
