### ISSUE TITLE
Verify Rewrite middleware for release

### ISSUE THREAD

**Issue by muratg** [aspnet/BasicMiddleware#73]
- Verify different flavors
  - Mod rewrite
  - URL rewrite
  - Code based
-  Missing functionality, and recommendations on adding any of those 
- API surface
- Test coverage
- Etc.

**Comment by muratg** [comment]
cc @ZestyBread @Tratcher

**Comment by ZestyBread** [comment]
@natemcmaster Recommend waiting until Monday after API review/ when changes are merged.

**Comment by natemcmaster** [comment]
Creating a list of issues that we should ensure we follow up on before release:

- [ ] https://github.com/aspnet/BasicMiddleware/issues/94 - if not implemented by release, we should remove ChangeEnvironmentAction and ChangeCookieAction. These are currently stub classes.
- [ ] https://github.com/aspnet/BasicMiddleware/issues/78 - common use case. Ensure our logging reveals enough detail to help users identify what went wrong.
- [ ] https://github.com/aspnet/BasicMiddleware/issues/81 - initial investigation shows that lots of rules can have a big perf hit. We need to provide ways to mitigate this.

**Comment by natemcmaster** [comment]
I've finished some microbenchmarking of the middleware. As we release the first version, it's important we make clear that this middleware should be used judiciously. (cc @danroth27 @DamianEdwards) Processing more than a few dozen rules should not be recommended. High numbers of rules (+100) can drag down the perf of a web app to an almost unusable point.

### Perf investigation results

Here are 5 benchmarks of the latest version of this middleware:
![rewrite_middleware_perf_chart](https://cloud.githubusercontent.com/assets/2696087/18803034/91b6bb5a-81a1-11e6-852d-b76606cb3011.png)

Apache mod_rewrite has a similar perf response. Here are three benchmarks comparing the middleware and mod_rewrite.

![apache_v_middleware](https://cloud.githubusercontent.com/assets/2696087/18803084/fa0382a6-81a1-11e6-9023-f0825b291d96.png)

I tried to obtain a similar comparison with IIS UrlRewrite module. The module performs so well that it did not show any statistically significant degradation of performance as the number of rules increased. IIS UrlRewrite is not a perf bottleneck for ≤ 1000 rules (at least for the scenarios tested in the microbenchmarks).

**Comment by Tratcher** [comment]
These comparisons are all between code rules in the middleware and mod rules in apache, correct? How well does the middleware's implementation of apache's and IIS's rules perform?

**Comment by natemcmaster** [comment]
> These comparisons are all between code rules in the middleware and mod rules in apache, correct? 

Yes, these are only tests of regex-matching rules. There are dozens of other scenarios, but matching URLs with a regex pattern is the most common which is why I chose it for some initial perf.

> How well does the middleware's implementation of apache's and IIS's rules perform?

Don't know. But I'd hypothesize our middleware is slower than Apache/IIS in most scenarios.
